Repository SharpDevOps10/NestAuth, pull requests merged in 2023-10, with the labels that each got.

#3 Added LICENSE
  LICENSE
Labels: documentation

#5 configurations #4: Added `prisma` configurations
  .gitignore
  package-lock.json
  package.json
  prisma/schema.prisma
Labels: configurations

#8 Create docker-compose.yml
  docker-compose.yml
Labels: configurations

#9 migration #6: added user table
  package-lock.json
  package.json
  prisma/migrations/20231015092459_added_user_modell/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: migration

#12 enhancement #10: added prisma service
  .eslintrc.js
  .prettierrc
  docker-compose.yml
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/auth/auth.module.ts
  src/main.ts
  src/prisma/prisma.module.ts
  src/prisma/prisma.service.ts
Labels: enhancement

#14 Added auth service and controller
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
Labels: enhancement

#16 Added information about `Prisma`
  README.md
Labels: documentation

#18 Merge Conflicts
  README.md
Labels: documentation

#20 Added auth DTO
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/AuthDTO.ts
  src/auth/dto/index.ts
  src/prisma/prisma.module.ts
Labels: enhancement

#26 enhancement #22: added types for tokens
  src/auth/dto/AuthDTO.ts
  src/auth/types/index.ts
  src/auth/types/tokens.types.ts
  src/main.ts
Labels: enhancement

#25 feature #21: implemented strategies
  package-lock.json
  package.json
  src/auth/auth.module.ts
  src/strategy /access.strategy.ts
  src/strategy /index.ts
  src/strategy /refresh.strategy.ts
Labels: feature

#27 feature #23: implemented user registration
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/prisma/prisma.module.ts
Labels: feature

#28 migration #24: unique id
  prisma/migrations/20231022113903_added_unique_id/migration.sql
  prisma/schema.prisma
Labels: migration

#32 enhancement #31: added func that updates rt
  package-lock.json
  package.json
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/prisma/prisma.module.ts
Labels: enhancement

#34 feature #33: implement logic for user authentication
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
Labels: feature

#36 feature #35: implemented logout functionality
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/strategy /access.strategy.ts
Labels: feature

#46 feature #45: added @Public decorator
  src/app.module.ts
  src/auth/auth.controller.ts
  src/common/decorators/index.ts
  src/common/decorators/public.ts
  src/common/guards/accessToken.guard.ts
  src/main.ts
Labels: feature

#48 bug #47: added @Public decorator
  src/auth/auth.controller.ts
  src/common/guards/accessToken.guard.ts
Labels: bug
